[package]
name = "adika-pdf-editor"
version = "1.12.0"
description = "Adika PDF Editor - privacy-first offline PDF editor"
authors = ["unupunct"]
license = "MIT"
edition = "2021"

[lib]
name = "adika_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
percent-encoding = "2"
cryptoki = "0.12.1"
sha2 = "0.11.0"
base64 = "0.23.1"
hex = "0.4.3"
ureq = "2"
tauri-plugin-opener = "2"
chrono = "0.4"
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2.13"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[target."cfg(windows)".dependencies]
schannel = "0.1.29"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_Security_Cryptography", "Win32_System_Console", "Win32_System_Com", "Win32_System_LibraryLoader", "Win32_System_JobObjects", "Win32_System_Mapi", "Win32_System_Threading"] }
